// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/req_res.proto

package grpc.entity;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cooze.grpc.entity.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   */
  String getSex();
  /**
   * <code>string sex = 2;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();
}
