// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/req_res.proto

package grpc.entity;

public interface AccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cooze.grpc.entity.AccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();

  /**
   * <code>repeated .org.cooze.grpc.entity.Account results = 3;</code>
   */
  java.util.List<Account>
      getResultsList();
  /**
   * <code>repeated .org.cooze.grpc.entity.Account results = 3;</code>
   */
  Account getResults(int index);
  /**
   * <code>repeated .org.cooze.grpc.entity.Account results = 3;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .org.cooze.grpc.entity.Account results = 3;</code>
   */
  java.util.List<? extends AccountOrBuilder>
      getResultsOrBuilderList();
  /**
   * <code>repeated .org.cooze.grpc.entity.Account results = 3;</code>
   */
  AccountOrBuilder getResultsOrBuilder(
      int index);
}
