// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity/req_res.proto

package grpc.entity;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.cooze.grpc.entity.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
